apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "dg-platform-agent.fullname" . }}-agent-pod-config
  labels:
    {{- include "dg-platform-agent.labels" . | nindent 4 }}
data:
  AGENT_POD_IMAGE: {{ .Values.agentPod.image.repository | quote }}
  AGENT_POD_TAG: {{ .Values.agentPod.image.tag | quote }}
