{{- if .Values.externalSecret.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "dg-platform-agent.fullname" . }}
  labels:
    {{- include "dg-platform-agent.labels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.externalSecret.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ include "dg-platform-agent.fullname" . }}
    creationPolicy: Owner
  {{- with .Values.externalSecret.data }}
  data:
    {{- range . }}
    - secretKey: {{ .secretKey }}
      remoteRef:
        key: {{ .remoteRef.key | quote }}
        {{- if .remoteRef.property }}
        property: {{ .remoteRef.property | quote }}
        {{- end }}
    {{- end }}
  {{- end }}
  {{- with .Values.externalSecret.dataFrom }}
  dataFrom:
    {{- range . }}
    - extract:
        key: {{ .key | quote }}
    {{- end }}
  {{- end }}
{{- end }}
