{{- if .Values.ghcr.externalSecret.enabled -}}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "dg-platform-agent.fullname" . }}-ghcr
  labels:
    {{- include "dg-platform-agent.labels" . | nindent 4 }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.ghcr.externalSecret.secretStoreRef.name }}
    kind: {{ .Values.ghcr.externalSecret.secretStoreRef.kind }}
  target:
    name: {{ include "dg-platform-agent.fullname" . }}-ghcr
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: .dockerconfigjson
      remoteRef:
        key: {{ .Values.ghcr.externalSecret.remoteRef.key | quote }}
{{- end }}
