{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "dg-platform-agent.fullname" . }}
  labels:
    {{- include "dg-platform-agent.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources:
      - pods
    verbs: [create, delete, get, list, watch]
  - apiGroups: [""]
    resources:
      - configmaps
      - secrets
      - services
    verbs: [get, list, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "dg-platform-agent.fullname" . }}
  labels:
    {{- include "dg-platform-agent.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "dg-platform-agent.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name | default (include "dg-platform-agent.fullname" .) }}
    namespace: {{ .Release.Namespace }}
{{- end }}
