{{- if .Values.warmPool.enabled -}}
apiVersion: extensions.agents.x-k8s.io/v1alpha1
kind: SandboxWarmPool
metadata:
  name: {{ include "dg-platform-agent.sandboxTemplateName" . }}-warmpool
  namespace: {{ include "dg-platform-agent.sandboxNamespace" . }}
  labels:
    {{- include "dg-platform-agent.labels" . | nindent 4 }}
spec:
  templateRef:
    name: {{ include "dg-platform-agent.sandboxTemplateName" . }}
  replicas: {{ .Values.warmPool.replicas }}
{{- end }}
