apiVersion: v1
kind: Service
metadata:
  name: {{ include "dg-platform-agent.fullname" . }}-controller
  labels:
    {{- include "dg-platform-agent.controller.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.controller.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "dg-platform-agent.controller.selectorLabels" . | nindent 4 }}
